FROM alpine:3.5

MAINTAINER docker@stefan-van-essen.nl

RUN apk -U upgrade && apk add \
    curl \
    nginx \
    php5 \
    php5-fpm \
    && rm -rf /var/cache/apk/* \
    && addgroup -S php \
    && adduser -S -G php php


COPY files/s6-overlay files/general files/php5 /

WORKDIR /www

ENTRYPOINT ["/init"]

HEALTHCHECK --interval=5s --timeout=5s CMD curl -f http://127.0.0.1 || exit 1
