FROM alpine:3.18

LABEL maintainer="docker@stefan-van-essen.nl"

RUN apk -U upgrade && apk add --no-cache \
    curl \
    nginx \
    php82-fpm \
    tzdata \
    && ln -s /usr/sbin/php-fpm82 /usr/sbin/php-fpm \
    && addgroup -S php \
    && adduser -S -G php php \
    && rm -rf /var/cache/apk/* /etc/nginx/http.d/* /etc/php82/conf.d/* /etc/php82/php-fpm.d/*

COPY files/s6-overlay files/general files/php82 /

WORKDIR /www

ENTRYPOINT ["/init"]

EXPOSE 80

HEALTHCHECK --interval=5s --timeout=5s CMD curl -f http://127.0.0.1/php-fpm-ping || exit 1
