FROM alpine:3.19

LABEL maintainer="docker@stefan-van-essen.nl"

RUN apk -U upgrade && apk add --no-cache \
    curl \
    nginx \
    php81-fpm \
    tzdata \
    && ln -s /usr/sbin/php-fpm81 /usr/sbin/php-fpm \
    && addgroup -S php \
    && adduser -S -G php php \
    && rm -rf /var/cache/apk/* /etc/nginx/http.d/* /etc/php81/conf.d/* /etc/php81/php-fpm.d/*

COPY files/s6-overlay files/general files/php81 /

WORKDIR /www

ENTRYPOINT ["/init"]

EXPOSE 80

HEALTHCHECK --interval=5s --timeout=5s CMD curl -f http://127.0.0.1/php-fpm-ping || exit 1
