FROM alpine:3.15

LABEL maintainer="juancbdm@gmail.com"

RUN apk -U upgrade && apk add --no-cache \
    curl \
    nginx \
    php8-fpm \
    tzdata \
    && ln -s /usr/sbin/php-fpm8 /usr/sbin/php-fpm \
    && addgroup -S php \
    && adduser -S -G php php \
    && rm -rf /var/cache/apk/* /etc/nginx/conf.d/* /etc/php8/conf.d/* /etc/php8/php-fpm.d/*

COPY files/s6-overlay files/general files/php8 /

WORKDIR /www

ENTRYPOINT ["/init"]

EXPOSE 80

HEALTHCHECK --interval=5s --timeout=5s CMD curl -f http://127.0.0.1/php-fpm-ping || exit 1
