FROM alpine:3.6

MAINTAINER docker@stefan-van-essen.nl

RUN apk -U upgrade && apk add \
    curl \
    nginx \
    php7-fpm \
    tzdata \
    && addgroup -S php \
    && adduser -S -G php php \
    && rm -rf /var/cache/apk/* /etc/nginx/conf.d/* /etc/php7/conf.d/* /etc/php7/php-fpm.d/*

COPY files/s6-overlay files/general files/php7 /

WORKDIR /www

ENTRYPOINT ["/init"]

HEALTHCHECK --interval=5s --timeout=5s CMD curl -f http://127.0.0.1/php-fpm-ping || exit 1
