FROM alpine:3.14

ADD https://php.hernandev.com/key/php-alpine.rsa.pub /etc/apk/keys/php-alpine.rsa.pub

RUN apk --update-cache add ca-certificates && \
    echo "https://php.hernandev.com/v3.14/php-8.1" >> /etc/apk/repositories

LABEL maintainer="docker@stefan-van-essen.nl"

RUN apk -U upgrade && apk add --no-cache \
    curl \
    nginx \
    php8-fpm \
    tzdata \
    && ln -s /usr/sbin/php-fpm8 /usr/sbin/php-fpm \
    && addgroup -S php \
    && adduser -S -G php php \
    && rm -rf /var/cache/apk/* /etc/nginx/conf.d/* /etc/php8/conf.d/* /etc/php8/php-fpm.d/*

COPY files/s6-overlay files/general files/php8 /

WORKDIR /www

ENTRYPOINT ["/init"]

EXPOSE 80

HEALTHCHECK --interval=5s --timeout=5s CMD curl -f http://127.0.0.1/php-fpm-ping || exit 1
